#	$NetBSD: Makefile,v 1.1 2007/06/09 13:31:56 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:31:56 dsieger Exp   -->

XMLDOCS+=	index
# XMLDOCS+=	hardware
XMLDOCS+=	history

.include "../../../share/mk/web.site.mk"
