#	$NetBSD: Makefile,v 1.5 2005/10/14 08:59:59 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.5 2005/10/14 08:59:59 rillig Exp   -->

LISTDOCS=	index.list
LISTCOLLECTION=	NetBSD-1.4.3

.include "../../../share/mk/web.site.mk"
