#	$NetBSD: Makefile,v 1.2 2007/08/26 15:42:29 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.2 2007/08/26 15:42:29 dsieger Exp   -->

XMLDOCS+=	call-it-a-duck 
XMLDOCS+=	crypto-export
XMLDOCS+=	disclaimer
XMLDOCS+=	embed
XMLDOCS+=	features
XMLDOCS+=	goals
XMLDOCS+=	history
XMLDOCS+=	index
XMLDOCS+=	interop 
XMLDOCS+=	portability 
XMLDOCS+=	redistribution
XMLDOCS+=	standards 
XMLDOCS+=	system
# XMLDOCS+=	roadmap

# DEPENDS.roadmap+=	escape-cvs-tags

# ROADMAPTAGS=	NetBSD

# escape-cvs-tags:	ROADMAP
# .for tag in ${ROADMAPTAGS}
# 	sed -e 's/^\(.*\)\$$\(${tag}.*\)\$$\(.*\)$$/\1%\2%\3/g' ROADMAP > ROADMAP.tmp && mv -f ROADMAP.tmp ROADMAP
# .endfor

.include "../../share/mk/web.site.mk"
