#	$NetBSD: Makefile,v 1.11 2007/05/24 13:40:07 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.11 2007/05/24 13:40:07 dsieger Exp   -->

XMLDOCS+=       index faq
XMLDOCS+=       hardware

.include "../../../share/mk/web.site.mk"
