#	$NetBSD: Makefile,v 1.9 2005/11/17 15:30:46 jschauma Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.9 2005/11/17 15:30:46 jschauma Exp   -->

# XMLDOCS+=       index

LISTDOCS+=	faq.list

.include "../../../share/mk/web.site.mk"
