#	$NetBSD: Makefile,v 1.10 2006/05/29 14:32:28 jschauma Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.10 2006/05/29 14:32:28 jschauma Exp   -->

# XMLDOCS+=       index faq

.include "../../../share/mk/web.site.mk"
