#	$NetBSD: Makefile,v 1.3 2008/11/02 23:34:33 hubertf Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.3 2008/11/02 23:34:33 hubertf Exp   -->

XMLDOCS+=       index faq
XMLDOCS+=       hardware
XMLDOCS+=       history
XMLDOCS+=       ps2
XMLDOCS+=       netbook

.include "../../../share/mk/web.site.mk"
