#	$NetBSD: Makefile,v 1.2 2008/04/16 21:07:06 hubertf Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.2 2008/04/16 21:07:06 hubertf Exp   -->

XMLDOCS+=       index faq
XMLDOCS+=       hardware
XMLDOCS+=       history
XMLDOCS+=       ps2
XMLDOCS+=       eee

.include "../../../share/mk/web.site.mk"
