#	$NetBSD: Makefile,v 1.1 2007/04/08 13:21:40 hubertf Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/04/08 13:21:40 hubertf Exp   -->

XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
