#	$NetBSD: Makefile,v 1.8 2007/04/06 23:14:56 hubertf Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.8 2007/04/06 23:14:56 hubertf Exp   -->

XMLDOCS+=	index
XMLDOCS+=	faq

.include "../../../share/mk/web.site.mk"
