#	$NetBSD: Makefile,v 1.1 2007/06/09 11:33:55 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:33:55 dsieger Exp   -->

XMLDOCS+=	index rasvpn

.include "../../../../share/mk/web.site.mk"
