#	$NetBSD: Makefile,v 1.2 2007/06/17 15:22:40 pavel Exp $

XMLDOCS+=	index:index.xsl,docbook-website::

index.html: ../group.xsl ../../share/xsl/selgrp.xsl ../developerdb.xml

.include "../../share/mk/web.site.mk"
