#	$NetBSD: Makefile,v 1.20 2007/01/10 17:28:25 darcy Exp $

SUBDIR+=	3rdparty

XMLDOCS+=	compiling index
XMLDOCS+=	packages:pkgsrc-home.xsl::
PARAMS.packages=	--stringparam autolayout-file ${AUTOLAYOUTFILE}

LISTDOCS+=	pkg-growth.list
LISTDOCS+=	pkg-growth-jpg.list

.include "../../share/mk/web.site.mk"
