# $NetBSD: Makefile,v 1.6 2006/07/30 12:40:25 rillig Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.6 2006/07/30 12:40:25 rillig Exp   -->

INPUT_FILTER=	iconv -f iso-2022-jp -t euc-jp
OUTPUT_FILTER=	iconv -f euc-jp -t iso-2022-jp

.include "../../../developers/features/features.mk"
