#	$NetBSD: Makefile,v 1.19 2007/12/02 22:25:47 weinem Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.19 2007/12/02 22:25:47 weinem Exp   -->

SUBDIR=		org

XMLDOCS+=	donations index hardware
# XMLDOCS+=	projects
# XMLDOCS+=	soc-application soc-projects

.include "../../share/mk/web.site.mk"
