#	$NetBSD: Makefile,v 1.18 2007/02/02 23:01:38 martin Exp $

SUBDIR=		org

XMLDOCS+=	donations index hardware
XMLDOCS+=	howto projects
XMLDOCS+=	soc-application soc-projects

.include "../share/mk/web.site.mk"
