#	$NetBSD: Makefile,v 1.24 2007/04/07 22:38:52 hubertf Exp $

SUBDIR+=	profiling
SUBDIR+=	pseudo

XMLDOCS+=	index kgdb non-exec ddwg porting_netbsd_arm_soc programming
XMLDOCS+=	lazyfpu uvm scsidma vfork
XMLDOCS+=	converting-ethernet-drivers
XMLDOCS+=	porting-freebsd-net
XMLDOCS+=	elf-notes

.include "../../share/mk/web.site.mk"
