#	$NetBSD: Makefile,v 1.1 2007/06/09 11:34:21 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:34:21 dsieger Exp   -->

XMLDOCS+=	index

.include "../../../../share/mk/web.site.mk"
