#	$NetBSD: Makefile,v 1.2 2007/06/12 14:30:33 reed Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.2 2007/06/12 14:30:33 reed Exp   -->

# for community

# XMLDOCS+=	groups
XMLDOCS+=	hackathon
XMLDOCS+=	index

.include "../../share/mk/web.site.mk"
