# $NetBSD: Makefile,v 1.6 2007/04/06 00:27:41 hubertf Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.6 2007/04/06 00:27:41 hubertf Exp   -->

XMLDOCS+=	serial

.include "../../../../share/mk/web.site.mk"
