# $NetBSD: Makefile,v 1.5 2005/10/14 08:59:55 rillig Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.5 2005/10/14 08:59:55 rillig Exp   -->

LISTDOCS+=	serial.list

.include "../../../../share/mk/web.site.mk"
