# $NetBSD: Makefile,v 1.8 2010/11/28 16:30:17 tonnerre Exp $

XMLDOCS+=	index patches-1.6.2 patches-1.6.1 patches-1.6
XMLDOCS+=	patches-1.5.3 patches-1.5.2 patches-1.5.1
XMLDOCS+=	patches-1.5 patches-2.0 advisory
XMLDOCS+=	patches-2.0.2 patches-2.0.3 patches-2.1
XMLDOCS+=	patches-3.0 patches-3.0.1 patches-3.0.2 
XMLDOCS+=	patches-3.1 patches-3.0.3 patches-3.1.1
XMLDOCS+=	patches-4.0 patches-4.0.1 patches-5.0
XMLDOCS+=	patches-5.0.1 patches-5.0.2 patches-5.1
XMLDOCS+=	release

.include "../../share/mk/web.site.mk"
