#	$NetBSD: Makefile,v 1.1 2007/06/09 13:32:24 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:32:24 dsieger Exp   -->

XMLDOCS+=	index
# XMLDOCS+=	install
# XMLDOCS+=	info

.include "../../../share/mk/web.site.mk"
