#	$NetBSD: Makefile,v 1.1 2007/06/08 15:26:35 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/08 15:26:35 dsieger Exp   -->

XMLDOCS+=	cdroms index

.include "../../share/mk/web.site.mk"
