# $NetBSD: Makefile,v 1.1 2007/06/09 11:33:05 dsieger Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.1 2007/06/09 11:33:05 dsieger Exp   -->

SUBDIR+=	MIPS

XMLDOCS+=	index

.include "../../../../share/mk/web.site.mk"
