#       $NetBSD: Makefile,v 1.9 2006/07/30 12:40:26 rillig Exp $
#       <!-- Based on english version: -->
#       <!-- NetBSD: Makefile,v 1.9 2006/07/30 12:40:26 rillig Exp   -->

INPUT_FILTER=		cat

.include "../../../gallery/in-Action/gallery.mk"
