#!/usr/bin/env perl
#	$NetBSD: mkact.pl,v 1.5 2007/01/24 04:21:28 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: mkact.pl,v 1.5 2007/01/24 04:21:28 rillig Exp   -->
#
# Reads index.act-template, and inserts and entries of the form
# @@@ENTRY: whatever            # comments are possible
# html files containing <IMG> tags are expected as $entry-img.html
# html files containing descriptions are expected as $entry-txt.html


$pic_left=0; 
$debug=0;

sub printfile {
    local($file)=@_;
    if ( ! -f $file && -f "../../../gallery/in-Action/$file" ) {
	$file = "../../../gallery/in-Action/$file";
    }
    open(F, "cat $file|") or die "Cannot open $file for reading: $!\n";
    while(<F>) {
	s/<!--.*//g;
	s#(href|src)="([^"/]+\.(png|gif|jpg))"#$1="../../../gallery/in-Action/$2"#gi;
	print "$_";
    }
    close(F);
}

my $lineno = 0;
while(<>) {
    $lineno++;

    if ($lineno == 2) {
	print "<!-- This file has been autogenerated by mkact.pl. -->\n";
    }

    if (/\@\@\@ENTRY: (\S*)\s+(\S*)/) {
	$entry=$1;
	$type=$2;

	print "\n<tr>\n";

        print "<td bgcolor=\"#000000\"><img src=\"../../../images/empty.gif\"";
        print " width=\"1\" height=\"1\" alt=\" \"></td>\n";
	print "<td bgcolor=\"#e8e8e8\" align=\"center\">$type</td>\n";
        print "<td bgcolor=\"#000000\"><img src=\"../../../images/empty.gif\"";
        print " width=\"1\" height=\"1\" alt=\" \"></td>\n";
	print "<td>\n";
	print "<tt>$entry:</tt><BR>\n"
	    if $debug;
	print ("\n<table cellpadding=\"5\"><tr>");
	
	if ($pic_left) {
	    print "<td>";
			  printfile "$entry-img.html"; print "</td>";
	    print "<td><a name=\"$entry\"></a>"; 
			  printfile "$entry-txt.html"; print "</td>";
	    
	    $pic_left=0;
	} else {
	    print "<td><a name=\"$entry\"></a>";
			  printfile "$entry-txt.html"; print "</td>";
	    print "<td>"; printfile "$entry-img.html"; print "</td>";
	    
	    $pic_left=1;
	}

	print ("</tr></table>\n\n</td>" .
	       "\n"
	       );

        print "<td bgcolor=\"#d8d8d8\"><img src=\"../../../images/empty.gif\"";
        print " width=\"1\" height=\"1\" alt=\" \"></td>\n";

        print ("</tr>\n\n");
        print "<tr>\n";
        print "<td bgcolor=\"#000000\"><img src=\"../../../images/empty.gif\"";
        print " width=\"1\" height=\"1\" alt=\" \"></td>\n";
        print "<td bgcolor=\"#000000\"><img src=\"../../../images/empty.gif\"";
        print " width=\"1\" height=\"1\" alt=\" \"></td>\n";
        print "<td bgcolor=\"#000000\"><img src=\"../../../images/empty.gif\"";
        print " width=\"1\" height=\"1\" alt=\" \"></td>\n";
        print "<td bgcolor=\"#d8d8d8\"><img src=\"../../../images/empty.gif\"";
	print " width=\"1\" height=\"1\" alt=\" \"></td>\n";
        print "<td bgcolor=\"#d8d8d8\"><img src=\"../../../images/empty.gif\"";
	print " width=\"1\" height=\"1\" alt=\" \"></td>\n</tr>\n";

    } else {
	print "$_";
    }
}
