#	$NetBSD: Makefile,v 1.1 2007/06/09 11:33:40 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:33:40 dsieger Exp   -->

SUBDIR+=	profiling
SUBDIR+=	pseudo

# XMLDOCS+=	index kgdb non-exec ddwg porting_netbsd_arm_soc programming
XMLDOCS+=	index kgdb programming
# XMLDOCS+=	lazyfpu uvm scsidma vfork
XMLDOCS+=	lazyfpu uvm vfork
# XMLDOCS+=	converting-ethernet-drivers
# XMLDOCS+=	porting-freebsd-net
XMLDOCS+=	elf-notes

.include "../../../share/mk/web.site.mk"
