#	$NetBSD: Makefile,v 1.1 2007/06/09 11:33:59 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:33:59 dsieger Exp   -->

# SUBDIR+=	rbootd

# XMLDOCS+=	index bootparams
XMLDOCS+=	index

.include "../../../../share/mk/web.site.mk"
