#	$NetBSD: Makefile,v 1.2 2009/08/15 16:55:58 snj Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.2 2009/08/15 16:55:58 snj Exp   -->

XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
