#!/usr/pkg/bin/perl
#
# $Id: mkbooks.pl,v 1.1 1999/04/19 07:46:05 sakamoto Exp $
#
require("jcode.pl");

@LINES = <STDIN>;
$string = join('', @LINES);
$string =~ s/\n//g;

&jcode'jis2euc(*string);

$itemnum = 0;
$itemf = 0;
@P = split(/</, $string);

foreach $p (@P) {
	local ($tag, $content) = split(/>/, $p);
	$tag =~ tr/A-Z/a-z/;
	$content =~ s/[ \t]+/ /g;
	$content =~ s/^[ ](.*)/$1/;
	$content =~ s/(.*)[ ]/$1/;

	check: {
		if ($tag eq "item") {
			if ($itemf) {
				die "Invalid item start "
					. ($itemnum + 1) . "\n";
			}
			$itemf = !$itemf;
			last check;
		} elsif ($tag eq "/item") {
			if (!$itemf) {
				die "Invalid item close $itemnum\n";
			}
			$itemf = !$itemf;
			$itemnum++;
			last check;
		}

		$item{$itemnum.$tag} = $content;
	}
}

open(LIST_REGISTER, '>books.html') || die "Can't open books.html $!";
&makelist_by_register(LIST_REGISTER);
close(LIST_REGISTER);

sub makelist_by_register {
	local($FD) = @_;

	&print_head($FD, "NetBSD-related BOOKS (by date)",
		"<h1>NetBSD 関連書籍(登録順)</h1>\n" .
		"<hr>\n");

	print $FD "<ul>\n";
	for ($i = 0; $i < $itemnum; $i++) {
		&print_title($FD, $i, $item{$i.'title'});
	}
	print $FD "</ul>\n<hr>\n<dl>\n";

	for ($i = 0; $i < $itemnum; $i++) {
		&print_item($FD, $i,
			$item{$i.'title'},
			$item{$i.'author'},
			$item{$i.'publisher'},
			$item{$i.'date'},
			$item{$i.'isbn'},
			$item{$i.'page'},
			$item{$i.'price'},
			$item{$i.'url'},
			$item{$i.'misc'});
	}
	&print_tail($FD);
}

sub print_head {
	local($FD, $title, $head) = @_;

	&jcode'euc2jis(*title);
	&jcode'euc2jis(*head);

	print $FD <<EOF;
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-2022-JP">
<!-- Copyright (c) 1999
	The Japan NetBSD Users' Group. ALL RIGHTS RESERVED. -->
<!-- DO NOT EDIT THIS FILE DIRECTLY - EDIT books.data AND RUN 'make'. -->
<link rev="made" href="mailto:www\@JP.NetBSD.ORG">
<title>$title</title>
</head>
<body bgcolor="#FFFFFF" text="#000000">
$head
EOF
}

sub print_tail {
	local($FD) = @_;

	print $FD <<EOF;
</dl>

<hr>
<address>
  www\@JP.NetBSD.ORG<br>
  \$Id\$<br>
  Copyright &copy; 1999
    The Japan NetBSD Users' Group.  ALL RIGHTS RESERVED.
</address>

</body>
</html>
EOF
}

sub print_title {
	local ($FD, $number, $title) = @_;

	&jcode'euc2jis(*title);
	print $FD "<li><a href=\"#item$number\">$title</a>\n";
}

sub print_item {
	local ($FD, $number, $title, $author, $publisher, $date,
		$isbn, $page, $price, $url, $misc) = @_;

	&jcode'euc2jis(*title);
	$author = &jcode'jis('<tr><th>著者<td>'.$author);
	$publisher = &jcode'jis('<tr><th>出版社<td>'.$publisher);
	$date = &jcode'jis('<tr><th>刊行日<td>'.$date);
	$isbn = "<tr><th>ISBN<td>$isbn";
	$page = &jcode'jis('<tr><th>ページ数<td>'.$page);
	$price = &jcode'jis('<tr><th>価格<td>'.$price.'円');
	$url = "<tr><th>WWW<td><a href=\"$url\">$url</a>";
	$misc = &jcode'jis('<tr><th>説明等<td>'.$misc.'<br>');

	print $FD <<EOF;
<p>
<dt><a name="item$number" href="#item$number">$title</a>
<dd><table border=1>
  $author
  $publisher
  $date
  $isbn
  $page
  $price
  $url
  $misc
  </table>

EOF
}
