#!/usr/pkg/bin/perl
#
# $Id: mklinks.pl,v 1.5 2000/08/25 00:40:11 tacha Exp $
#
# <ITEM>
# <TITLE>
# <URL>
# <KEYWORD>
# <DESCRIPTION>
# </ITEM>
#
require("jcode.pl");

@LINES = <STDIN>;
$string = join('', @LINES);
$string =~ s/\n//g;

&jcode'jis2euc(*string);

$itemnum = 0;
$itemf = 0;
@P = split(/</, $string);

foreach $p (@P) {
	local ($tag, $content) = split(/>/, $p);
	$tag =~ tr/A-Z/a-z/;
	$content =~ s/[ \t]+/ /g;
	$content =~ s/^[ ](.*)/$1/;
	$content =~ s/(.*)[ ]/$1/;

	check: {
		if ($tag eq "item") {
			if ($itemf) {
				die "Invalid item start "
					. ($itemnum + 1) . "\n";
			}
			$itemf = !$itemf;
			last check;
		} elsif ($tag eq "/item") {
			if (!$itemf) {
				die "Invalid item close $itemnum\n";
			}
			$itemf = !$itemf;
			$itemnum++;
			last check;
		}

		$item{$itemnum.$tag} = $content;
	}
}

open(LIST_REGISTER, '>links.html') || die "Can't open links.html $!";
&makelist_by_register(LIST_REGISTER);
close(LIST_REGISTER);

open(LIST_ARCH, '>arch.html') || die "Can't open arch.html $!";
&makelist_by_arch(LIST_ARCH);
close(LIST_ARCH);

sub makelist_by_register {
	local($FD) = @_;

	&print_head($FD, "NetBSD-related LINKS (by registered)",
		"<h1>NetBSD 関連リンク(登録順)</h1>\n" .
		"<hr>\n");
	for ($i = 0; $i < $itemnum; $i++) {
		&print_item($FD, $i,
			$item{$i.'title'}, $item{$i.'url'},
			$item{$i.'keyword'}, $item{$i.'description'});
	}
	&print_tail($FD);
}

sub makelist_by_arch {
	local($FD) = @_;
	local($i, $j, $f);
	local(%arch_index);
	local(@arch_num);
	local(@arch_name) = (
		'COMMON',
		'I386',
		'MAC68K',
		'MACPPC',
		'PC98',
		'X68K',
		'SUN3',
		'NEWSMIPS',
		'BEBOX',
		'SH3'
	);

	&print_head($FD, "NetBSD-related LINKS (by architecture)",
		"<h1>NetBSD 関連リンク(アーキテクチャー別)</h1>\n");

	for ($j = 0; $j <= $#arch_name; $j++) {
		local($an);
		($an = $arch_name[$j]) =~ tr/A-Z/a-z/;
		print $FD <<EOF;
<dt><a href="#$arch_name[$j]">$an</a><br>
EOF
	}

	for ($i = 0; $i < $itemnum; $i++) {
		local(@k) = split(/,/, $item{$i.'keyword'});
		local($kw);

		$f = 0;
		foreach $kw (@k) {
			for ($j = 1; $j <= $#arch_name; $j++) {
				if ($kw eq $arch_name[$j]) {
					$f++;
					$arch_index{$j, $arch_num[$j]++} = $i;
				}
			}
		}
		if ($f == 0) {
			$arch_index{0, $arch_num[0]++} = $i;
		}
	}

	for ($j = 0; $j <= $#arch_name; $j++) {
		local($an, $num);
		($an = $arch_name[$j]) =~ tr/A-Z/a-z/;
		print $FD <<EOF;
</dl>
<hr>
<h2><a name="$arch_name[$j]">$an</a></h2>
<dl>
EOF

		for ($num = 0; $num < $arch_num[$j]; $num++) {
			$i = $arch_index{$j, $num};
			&print_item($FD, $i,
				$item{$i.'title'}, $item{$i.'url'},
				$item{$i.'keyword'},
				$item{$i.'description'});
		}
	}
	&print_tail($FD);
}

sub print_head {
	local($FD, $title, $head) = @_;

	&jcode'euc2jis(*title);
	&jcode'euc2jis(*head);

	print $FD <<EOF;
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-2022-JP">
<!-- Copyright (c) 1999, 2000
	The Japan NetBSD Users' Group. ALL RIGHTS RESERVED. -->
<!-- DO NOT EDIT THIS FILE DIRECTLY - EDIT links.data AND RUN 'make'. -->
<link rev="made" href="mailto:www\@JP.NetBSD.ORG">
<title>$title</title>
</head>
<body bgcolor="#FFFFFF" text="#000000">
$head
<dl>
EOF
}

sub print_tail {
	local($FD) = @_;

	print $FD <<EOF;
</dl>

<hr>
<address>
  www\@JP.NetBSD.ORG<br>
  \$Id\$<br>
  Copyright &copy; 1999, 2000
    The Japan NetBSD Users' Group.  ALL RIGHTS RESERVED.
</address>

</body>
</html>
EOF
}

sub print_item {
	local ($FD, $number, $title, $url, $keyword, $description) = @_;

	&jcode'euc2jis(*title);
	&jcode'euc2jis(*description);

	print $FD <<EOF;
<p>
<dt><a name="item$number" href="$url">$title</a>
<dd>
  Keyword: $keyword<br>
  $description

EOF
}
