#!/usr/pkg/bin/perl
#
# $Id: mklinks.pl,v 1.1 1999/02/12 08:47:48 sakamoto Exp $
#
# <ITEM>
# <TITLE>
# <URL>
# <KEYWORD>
# <DESCRIPTION>
# </ITEM>
#
require("jcode.pl");

@LINES = <STDIN>;
$string = join('', @LINES);
$string =~ s/\n//g;

&jcode'jis2euc(*string);

$item = 0;
$itemf = 0;
@P = split(/</, $string);

foreach $p (@P) {
	local ($tag, $content) = split(/>/, $p);
	$tag =~ y/A-Z/a-z/;
	$content =~ s/[ \t]+/ /g;
	$content =~ s/^[ ](.*)/$1/;
	$content =~ s/(.*)[ ]/$1/;

	check: {
		if ($tag eq "item") {
			if ($itemf) {
				die "Invalid item start " . ($item + 1) . "\n";
			}
			$itemf = !$itemf;
			last check;
		}

		if ($tag eq "title") {
			$item_title[$item] = $content;
			last check;
		}

		if ($tag eq "url") {
			$item_url[$item] = $content;
			last check;
		}

		if ($tag eq "keyword") {
			$item_keyword[$item] = $content;
			last check;
		}

		if ($tag eq "description") {
			$item_description[$item] = $content;
			last check;
		}

		if ($tag eq "/item") {
			if (!$itemf) {
				die "Invalid item close $item\n";
			}
			$itemf = !$itemf;
			$item++;
			last check;
		}
	}
}

&makelist_by_register(STDOUT);





sub makelist_by_register {
	local($FD) = @_;

	&print_head($FD, "NetBSD-related LINKS",
		"<h1>NetBSD 関連リンク</h1>\n" .
		"NetBSD 関連のリンク集です。<br>\n" .
		"NetBSDに関するコンテンツの情報は " .
		"<a href=\"mailto:www-changes-ja\@jp.netbsd.org\">" .
		"www-changes-ja\@jp.netbsd.org</a>" .
		"までお寄せください。" .
		"<hr>\n");
	for ($i = 0; $i < $item; $i++) {
		&print_item($FD, $i,
			$item_title[$i], $item_url[$i],
			$item_keyword[$i], $item_description[$i]);
	}
	&print_tail($FD);
}

sub print_head {
	local($FD, $title, $head) = @_;

	&jcode'euc2jis(*title);
	&jcode'euc2jis(*head);

	print $FD <<EOF;
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-2022-JP">
<!-- Copyright (c) 1999
	The Japan NetBSD Users' Group. ALL RIGHTS RESERVED. -->
<!-- DO NOT EDIT THIS FILE DIRECTLY - EDIT links.data AND RUN 'make'. -->
<link rev="made" href="mailto:www\@JP.NetBSD.ORG">
<title>$title</title>
</head>
<body bgcolor="#FFFFFF" text="#000000">
$head
<dl>
EOF
}

sub print_tail {
	local($FD) = @_;

	print $FD <<EOF;
</dl>

<hr>
<address>
  www\@JP.NetBSD.ORG<br>
  \$Id\$<br>
  Copyright &copy; 1999
    The Japan NetBSD Users' Group.  ALL RIGHTS RESERVED.
</address>

</body>
</html>
EOF
}

sub print_item {
	local ($FD, $number, $title, $url, $keyword, $description) = @_;

	&jcode'euc2jis(*title);
	&jcode'euc2jis(*description);

	print $FD <<EOF;
<p>
<dt><a name="item$number" href="$url">$title</a>
<dd>
  Keyword: $keyword<br>
  $description

EOF
}
