#	$NetBSD: Makefile,v 1.1 2007/06/09 13:31:46 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:31:46 dsieger Exp   -->
#	Process .list files into .html files

# XMLDOCS+=	index faq multiafaq
XMLDOCS+=	index
# XMLDOCS+=	models
# XMLDOCS+=	history

.include "../../../share/mk/web.site.mk"
