#	$NetBSD: Makefile,v 1.6 2005/10/14 08:59:58 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.6 2005/10/14 08:59:58 rillig Exp   -->
#	Process .list files into .html files

LISTDOCS=	info-3.list
LISTDOCS+=	info-4.list
LISTDOCS+=	info-5.list
LISTDOCS+=	info-6.list
LISTDOCS+=	info-7.list
LISTDOCS+=	info-8.list
LISTDOCS+=	info-9.list

.include "../../../../share/mk/web.site.mk"
