#	$NetBSD: Makefile,v 1.4 2007/06/08 13:58:02 dsieger Exp $

XMLDOCS+=	index
XMLDOCS+=	search
XMLDOCS+=	send-pr
XMLDOCS+=	query-pr

SUBDIR+=	hardware
SUBDIR+=	security

.include "../share/mk/web.site.mk"
