#	$NetBSD: Makefile,v 1.5 2007/11/03 23:51:56 weinem Exp $

XMLDOCS+=	index
XMLDOCS+=	search
XMLDOCS+=	send-pr
XMLDOCS+=	query-pr
XMLDOCS+=	no-bugs

SUBDIR+=	hardware
SUBDIR+=	security

.include "../share/mk/web.site.mk"
