#	$NetBSD: Makefile,v 1.11 2007/05/26 11:12:52 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.11 2007/05/26 11:12:52 dsieger Exp   -->

XMLDOCS+=	index
XMLDOCS+=	faq
XMLDOCS+=	history
XMLDOCS+=	install
XMLDOCS+=	models

.include "../../../share/mk/web.site.mk"
