# $NetBSD: Makefile,v 1.12 2007/04/07 19:38:17 hubertf Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.12 2007/04/07 19:38:17 hubertf Exp   -->

XMLDOCS=	# start
XMLDOCS+=	branch
XMLDOCS+=	index
XMLDOCS+=	modules
XMLDOCS+=	notes
XMLDOCS+=	cvs_intro

.include "../../../share/mk/web.site.mk"
