# $NetBSD: Makefile,v 1.9 2005/12/24 12:23:25 daniel Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.9 2005/12/24 12:23:25 daniel Exp   -->

# XMLDOCS=	index notes

LISTDOCS=	branch.list

.include "../../../share/mk/web.site.mk"
