# $NetBSD: Makefile,v 1.1 2007/06/09 11:32:57 dsieger Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.1 2007/06/09 11:32:57 dsieger Exp   -->

# SUBDIR+=	Busses
SUBDIR+=	Chips
SUBDIR+=	Machines
SUBDIR+=	Misc

XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
