#	$NetBSD: Makefile,v 1.5 2008/09/25 15:24:03 tsutsui Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.5 2008/09/25 15:24:03 tsutsui Exp   -->

XMLDOCS+=	index
XMLDOCS+=	NetBSD-4.0:announcement.xsl,docbook-website::
XMLDOCS+=	NetBSD-4.0.1:announcement.xsl,docbook-website::

#changes.mdoc is a fragment to be pasted to src/distrib/notes/common/main,
#do not commit it directly
# XMLDOCS+=	relnotes:changes2relnotes.xsl:NetBSD-4.0.xml:changes.mdoc

.include "../../../share/mk/web.site.mk"
