#	$NetBSD: Makefile,v 1.1 2007/06/09 11:33:50 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:33:50 dsieger Exp   -->

SUBDIR=	smbprint

XMLDOCS=	index
# XMLDOCS+=	puffs

.include "../../../share/mk/web.site.mk"
