#	$NetBSD: Makefile,v 1.11 2007/04/07 09:00:10 hubertf Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.11 2007/04/07 09:00:10 hubertf Exp   -->

XMLDOCS+=	index faq

.include "../../../share/mk/web.site.mk"
