#	$NetBSD: Makefile,v 1.10 2005/10/14 08:59:58 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.10 2005/10/14 08:59:58 rillig Exp   -->

LISTDOCS+=	faq.list

# XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
