#	$NetBSD: Makefile,v 1.1 2007/06/09 13:31:48 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:31:48 dsieger Exp   -->
#	Process .list files into .html files

XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
