#	$NetBSD: Makefile,v 1.1 2007/06/09 12:59:09 dsieger Exp $

XMLDOCS+=	current formal index release-map

#SUBDIR+=	formal-0.8
#SUBDIR+=	formal-0.9
#SUBDIR+=	formal-1.0
#SUBDIR+=	formal-1.1
#SUBDIR+=	formal-1.2
#SUBDIR+=	formal-1.3
SUBDIR+=	formal-1.4
SUBDIR+=	formal-1.5
SUBDIR+=	formal-1.6
SUBDIR+=	formal-2.0
SUBDIR+=	formal-3

.include "../share/mk/web.site.mk"
