#	$NetBSD: Makefile,v 1.1 2007/06/09 12:59:19 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 12:59:19 dsieger Exp   -->

LISTDOCS=	NetBSD-1.5.1.list NetBSD-1.5.2.list NetBSD-1.5.3.list
LISTDOCS+=	index.list
LISTCOLLECTION=	NetBSD-1.5

.include "../../../share/mk/web.site.mk"
