#	$NetBSD: Makefile,v 1.14 2007/05/26 17:49:10 dsieger Exp $

XMLDOCS+=	index
XMLDOCS+=	faq
XMLDOCS+=	board-list
XMLDOCS+=	development
XMLDOCS+=	history
XMLDOCS+=	install

.include "../../share/mk/web.site.mk"
