#	$NetBSD: Makefile,v 1.10 2007/04/08 12:50:37 hubertf Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.10 2007/04/08 12:50:37 hubertf Exp   -->

XMLDOCS+=	index
# XMLDOCS+=	faq

.include "../../../share/mk/web.site.mk"
