#	$NetBSD: Makefile,v 1.1 2007/06/09 13:32:57 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:32:57 dsieger Exp   -->

XMLDOCS+=	index
# XMLDOCS+=	faq
# XMLDOCS+=	board-list
# XMLDOCS+=	development
# XMLDOCS+=	history
# XMLDOCS+=	install

.include "../../../share/mk/web.site.mk"
