# $NetBSD: Makefile,v 1.4 2010/05/20 15:50:00 tsutsui Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.4 2010/05/20 15:50:00 tsutsui Exp   -->

SUBDIR+=	acorn26
SUBDIR+=	acorn32
SUBDIR+=	algor
SUBDIR+=	alpha
SUBDIR+=	amd64
SUBDIR+=	amiga
SUBDIR+=	amigappc
SUBDIR+=	arc
SUBDIR+=	arm
SUBDIR+=	arm26
SUBDIR+=	arm32
SUBDIR+=	atari
SUBDIR+=	bebox
SUBDIR+=	cats
SUBDIR+=	cesfic
SUBDIR+=	cobalt
SUBDIR+=	dreamcast
SUBDIR+=	evbarm
SUBDIR+=	evbmips
SUBDIR+=	evbsh3
SUBDIR+=	evbppc
SUBDIR+=	ews4800mips
SUBDIR+=	hp300
SUBDIR+=	hp700
SUBDIR+=	hpcarm
SUBDIR+=	hpcmips
SUBDIR+=	hpcsh
SUBDIR+=	i386
SUBDIR+=	ia64
SUBDIR+=	ibmnws
SUBDIR+=	iyonix
SUBDIR+=	landisk
SUBDIR+=	luna68k
SUBDIR+=	mac68k
SUBDIR+=	macppc
SUBDIR+=	mipsco
SUBDIR+=	mmeye
SUBDIR+=	mvme68k
SUBDIR+=	mvmeppc
SUBDIR+=	netwinder
SUBDIR+=	news68k
SUBDIR+=	newsmips
SUBDIR+=	next68k
SUBDIR+=	ofppc
# SUBDIR+=	pc532
SUBDIR+=	pdp10
SUBDIR+=	playstation2
SUBDIR+=	pmax
SUBDIR+=	pmppc
SUBDIR+=	prep
SUBDIR+=	rs6000
SUBDIR+=	s390
SUBDIR+=	sandpoint
SUBDIR+=	sbmips
SUBDIR+=	sgimips
SUBDIR+=	sh3
SUBDIR+=	shark
SUBDIR+=	sparc
SUBDIR+=	sparc64
SUBDIR+=	sun2
SUBDIR+=	sun3
SUBDIR+=	vax
SUBDIR+=	x68k
SUBDIR+=	xen
SUBDIR+=	zaurus

XMLDOCS+=	index
XMLDOCS+=	emulators
XMLDOCS+=	history

.include "../../share/mk/web.site.mk"
