#	$NetBSD: Makefile,v 1.2 2009/08/15 02:26:44 snj Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.2 2009/08/15 02:26:44 snj Exp   -->

XMLDOCS+=	index
XMLDOCS+=	pmppcfaq

.include "../../../share/mk/web.site.mk"
