#	$NetBSD: Makefile,v 1.1 2007/06/09 13:31:43 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:31:43 dsieger Exp   -->

# XMLDOCS+=	index todo unsupported
XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
