#	$NetBSD: Makefile,v 1.1 2007/06/09 13:32:12 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:32:12 dsieger Exp   -->

XMLDOCS+=	index
XMLDOCS+=	compat-pmax
# XMLDOCS+=	howto-develop
XMLDOCS+=	howto-use
XMLDOCS+=	faq
# XMLDOCS+=	mgl2
# XMLDOCS+=	pocketv6
# XMLDOCS+=	todo

.include "../../../share/mk/web.site.mk"
