# $NetBSD: Makefile,v 1.7 2007/05/24 23:24:54 dsieger Exp $

SUBDIR=		info

XMLDOCS+=	index
XMLDOCS+=	meta-faq
XMLDOCS+=	hardware
XMLDOCS+=	history
XMLDOCS+=	todo

.include "../../share/mk/web.site.mk"
