# $NetBSD: Makefile,v 1.1 2007/06/09 13:32:25 dsieger Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.1 2007/06/09 13:32:25 dsieger Exp   -->

# SUBDIR=		info

XMLDOCS+=	index
XMLDOCS+=	meta-faq
XMLDOCS+=	hardware
XMLDOCS+=	history
XMLDOCS+=	todo

.include "../../../share/mk/web.site.mk"
