# $NetBSD: Makefile,v 1.2 2005/10/14 08:59:58 rillig Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.2 2005/10/14 08:59:58 rillig Exp   -->

SUBDIR=		info
SUBDIR+=	meta-faq

.include "../../../share/mk/web.site.mk"
