# $NetBSD: Makefile,v 1.4 2005/10/14 08:59:55 rillig Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.4 2005/10/14 08:59:55 rillig Exp   -->

# SUBDIR+=	Machines Misc
SUBDIR+=	Misc

.include "../../../share/mk/web.site.mk"
