# $NetBSD: Makefile,v 1.6 2006/07/30 14:05:48 rillig Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.6 2006/07/30 14:05:48 rillig Exp   -->

SUBDIR+=	Busses
SUBDIR+=	Chips
SUBDIR+=	Machines
SUBDIR+=	Misc

XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
