#	$NetBSD: Makefile,v 1.1 2007/06/09 12:59:25 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 12:59:25 dsieger Exp   -->

XMLDOCS+=	index NetBSD-3.0
# XMLDOCS+=	NetBSD-3.0.1
XMLDOCS+=	NetBSD-3.1
# XMLDOCS+=	NetBSD-3.0.2

.include "../../../share/mk/web.site.mk"
