#	$NetBSD: Makefile,v 1.1 2007/06/09 13:32:06 dsieger Exp $

XMLDOCS+=	index
XMLDOCS+=	dca.cable
XMLDOCS+=	dcmpinouts
XMLDOCS+=	domain.commands
XMLDOCS+=	faq
XMLDOCS+=	hardware
XMLDOCS+=	serialconsole
XMLDOCS+=	serialconsole380
XMLDOCS+=	serial.splitter
XMLDOCS+=	wishlist

.include "../../share/mk/web.site.mk"
