#	$NetBSD: Makefile,v 1.16 2007/05/25 22:20:28 dsieger Exp $

XMLDOCS+=	faq
XMLDOCS+=	index
XMLDOCS+=	models
XMLDOCS+=	nvedit
XMLDOCS+=	oldfaq
XMLDOCS+=	partitioning
XMLDOCS+=	x11

.include "../../share/mk/web.site.mk"
