#	$NetBSD: Makefile,v 1.1 2007/06/09 13:32:38 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:32:38 dsieger Exp   -->

XMLDOCS+=	faq
XMLDOCS+=	index
XMLDOCS+=	models
XMLDOCS+=	nvedit
XMLDOCS+=	oldfaq
XMLDOCS+=	partitioning
XMLDOCS+=	x11

.include "../../../share/mk/web.site.mk"
