# $NetBSD: Makefile,v 1.1 2007/06/08 13:58:05 dsieger Exp $

XMLDOCS+=	ata cardbus eisa i2c index
XMLDOCS+=	isa mca mii ofw pci pcmcia
XMLDOCS+=	podulebus pseudo-device sbus scsipi
XMLDOCS+=	tc usb vme

.include "../../share/mk/web.site.mk"
