#	$NetBSD: Makefile,v 1.1 2007/06/09 12:59:21 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 12:59:21 dsieger Exp   -->

# XMLDOCS+=	NetBSD-1.6.2
LISTDOCS+=	index.list NetBSD-1.6.list NetBSD-1.6.1.list
LISTCOLLECTION=	NetBSD-1.6

.include "../../../share/mk/web.site.mk"
