#	$NetBSD: Makefile,v 1.11 2005/10/14 08:59:59 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.11 2005/10/14 08:59:59 rillig Exp   -->

# XMLDOCS+=	NetBSD-1.6.2
LISTDOCS+=	index.list NetBSD-1.6.list NetBSD-1.6.1.list
LISTCOLLECTION=	NetBSD-1.6

.include "../../../share/mk/web.site.mk"
