#	$NetBSD: Makefile,v 1.1 2007/06/09 13:31:55 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:31:55 dsieger Exp   -->

XMLDOCS+=	index
# XMLDOCS+=	faq
XMLDOCS+=	history
# XMLDOCS+=	todo

.include "../../../share/mk/web.site.mk"
