#	$NetBSD: Makefile,v 1.10 2007/05/23 21:57:01 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.10 2007/05/23 21:57:01 dsieger Exp   -->

XMLDOCS+=	index
# XMLDOCS+=	faq
XMLDOCS+=	history
# XMLDOCS+=	todo

.include "../../../share/mk/web.site.mk"
