#	$NetBSD: Makefile,v 1.1 2007/06/09 13:33:14 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:33:14 dsieger Exp   -->

XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
