#	$NetBSD: Makefile,v 1.1 2007/06/09 13:31:59 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:31:59 dsieger Exp   -->

XMLDOCS+=	index
# XMLDOCS+=	faq
XMLDOCS+=	restorecd-howto

.include "../../../share/mk/web.site.mk"
