#	$NetBSD: Makefile,v 1.1 2007/06/09 11:33:53 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:33:53 dsieger Exp   -->

# SUBDIR+=	ipsec ipv6 isdn nsps pppoe netboot
SUBDIR+=	pppoe

# XMLDOCS+=	dhcp index gprs pf wavelan

.include "../../../share/mk/web.site.mk"
