#	$NetBSD: Makefile,v 1.5 2005/10/14 08:59:56 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.5 2005/10/14 08:59:56 rillig Exp   -->

LISTDOCS+=	index.list

.include "../../../../share/mk/web.site.mk"
