#	$NetBSD: Makefile,v 1.6 2007/04/07 00:27:59 hubertf Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.6 2007/04/07 00:27:59 hubertf Exp   -->

XMLDOCS+=	index

.include "../../../../share/mk/web.site.mk"
