#	$NetBSD: Makefile,v 1.1 2007/06/09 11:34:47 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:34:47 dsieger Exp   -->

# SUBDIR+=	3rdparty

XMLDOCS+=	compiling
XMLDOCS+=	index
XMLDOCS+=	pkg-growth
XMLDOCS+=	pkg-growth-jpg
XMLDOCS+=	packages:pkgsrc-home.xsl,docbook-website::

.include "../../../share/mk/web.site.mk"
