#	$NetBSD: Makefile,v 1.5 2005/10/14 08:59:58 rillig Exp $
#	Process .list files into .html files

LISTDOCS=	meta-faq-1.list
LISTDOCS+=	meta-faq-2.list
LISTDOCS+=	meta-faq-3.list
LISTDOCS+=	meta-faq-4.list
LISTDOCS+=	meta-faq-5.list
LISTDOCS+=	meta-faq-6.list
LISTDOCS+=	meta-faq-7.list
LISTDOCS+=	meta-faq-8.list

.include "../../../share/mk/web.site.mk"
