#	$NetBSD: Makefile,v 1.1 2007/06/09 13:33:11 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:33:11 dsieger Exp   -->

XMLDOCS+=	index
XMLDOCS+=	faq

.include "../../../share/mk/web.site.mk"
