#	$NetBSD: Makefile,v 1.1 2007/06/09 11:32:53 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 11:32:53 dsieger Exp   -->

SUBDIR+=	Hardware
# SUBDIR+=	bsd
SUBDIR+=	cross
SUBDIR+=	current
# SUBDIR+=	internals
SUBDIR+=	kernel
SUBDIR+=	misc
SUBDIR+=	network
# SUBDIR+=	pkgsrc
SUBDIR+=	power-mgmt
# SUBDIR+=	research
SUBDIR+=	software
SUBDIR+=	x

XMLDOCS+=	books
XMLDOCS+=	bootcd
XMLDOCS+=	compat
# XMLDOCS+=	elf
XMLDOCS+=	index
XMLDOCS+=	mirror
XMLDOCS+=	updating
# XMLDOCS+=	vmware

.include "../../share/mk/web.site.mk"
