# $NetBSD: Makefile,v 1.96 2007/06/12 10:54:45 dsieger Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.96 2007/06/12 10:54:45 dsieger Exp   -->

SUBDIR=		about
SUBDIR+=	changes
SUBDIR+=	community
SUBDIR+=	contrib
SUBDIR+=	developers
SUBDIR+=	docs
SUBDIR+=	donations
# SUBDIR+=	errors
# SUBDIR+=	foundation
SUBDIR+=	gallery
# SUBDIR+=	images
SUBDIR+=	mailinglists
# SUBDIR+=	mirrors
SUBDIR+=	releases
# SUBDIR+=	releng
SUBDIR+=	people
SUBDIR+=	ports
SUBDIR+=	sites
SUBDIR+=	support

.include "../share/mk/language.mk"
.include "../share/mk/web.site.mk"
