#	$NetBSD: Makefile,v 1.1 2007/06/09 13:33:18 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:33:18 dsieger Exp   -->

# XMLDOCS+=	index howto
XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
