#	$NetBSD: Makefile,v 1.1 2007/06/09 13:32:49 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:32:49 dsieger Exp   -->

XMLDOCS+=	faq
XMLDOCS+=	index

.include "../../../share/mk/web.site.mk"
