#	$NetBSD: Makefile,v 1.46 2007/08/29 09:39:54 dsieger Exp $
# <!-- Based on english version: -->
# <!-- NetBSD: Makefile,v 1.46 2007/08/29 09:39:54 dsieger Exp   -->

SUBDIR+=	cvs-repos
SUBDIR+=	features
# SUBDIR+=	pkgsrc
SUBDIR+=	releng

XMLDOCS+=	index
# XMLDOCS+=	announce
# XMLDOCS+=	commit-guidelines
# XMLDOCS+=	de-lint
XMLDOCS+=	htdocs
# XMLDOCS+=	manpages
# XMLDOCS+=	mirrors
XMLDOCS+=	new-port
# XMLDOCS+=	notes
XMLDOCS+=	PR
XMLDOCS+=	pgp
# XMLDOCS+=	restricted
# XMLDOCS+=	security
XMLDOCS+=	translate
# XMLDOCS+=	style
# XMLDOCS+=	www

# LISTDOCS+=	translate-german.list translate-french.list
# LISTDOCS+=	translate-spanish.list

.include "../../share/mk/web.site.mk"
