#	$NetBSD: Makefile,v 1.4 2005/10/14 08:59:57 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.4 2005/10/14 08:59:57 rillig Exp   -->

LISTDOCS+=	faq.list

.include "../../../share/mk/web.site.mk"
