#	$NetBSD: Makefile,v 1.1 2007/06/09 13:32:09 dsieger Exp $

XMLDOCS+=	index
XMLDOCS+=	boot_admin
XMLDOCS+=	faq
XMLDOCS+=	serialconsole
XMLDOCS+=	serialconsole-712

.include "../../share/mk/web.site.mk"
