#	$NetBSD: Makefile,v 1.9 2007/05/24 12:12:45 dsieger Exp $

XMLDOCS+=	index
XMLDOCS+=	boot_admin
XMLDOCS+=	faq
XMLDOCS+=	serialconsole
XMLDOCS+=	serialconsole-712

.include "../../share/mk/web.site.mk"
