#	$NetBSD: Makefile,v 1.9 2007/01/03 17:24:29 wennmach Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.9 2007/01/03 17:24:29 wennmach Exp   -->

# XSLFILE=	index.xsl

XMLDOCS+=	index

# XMLDOCS+=	2003:index.xsl:2003.xml:2003.html
# PARAMS.2003=	--stringparam autolayout-file  ${AUTOLAYOUTFILE}
# 
# XMLDOCS+=	2004:index.xsl:2004.xml:2004.html
# PARAMS.2004=	--stringparam autolayout-file  ${AUTOLAYOUTFILE}
# 
# XMLDOCS+=	2005:index.xsl:2005.xml:2005.html
# PARAMS.2005=	--stringparam autolayout-file  ${AUTOLAYOUTFILE}
# 
# XMLDOCS+=	2006:index.xsl:2006.xml:2006.html
# PARAMS.2006=	--stringparam autolayout-file  ${AUTOLAYOUTFILE}
# 
# XMLDOCS+=	2007:index.xsl:2007.xml:2007.html
# PARAMS.2007=	--stringparam autolayout-file  ${AUTOLAYOUTFILE}

.include "../../share/mk/web.site.mk"
