#	$NetBSD: Makefile,v 1.6 2005/10/14 09:00:00 rillig Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.6 2005/10/14 09:00:00 rillig Exp   -->

XMLDOCS+=	help brains toshiba

.include "../../../share/mk/web.site.mk"
