#	$NetBSD: Makefile,v 1.8 2008/03/23 13:18:30 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.8 2008/03/23 13:18:30 dsieger Exp   -->

XMLDOCS+=	brains
XMLDOCS+=	index
XMLDOCS+=	toshiba

.include "../../../share/mk/web.site.mk"
