#	$NetBSD: Makefile,v 1.1 2007/06/09 13:33:07 dsieger Exp $
#	<!-- Based on english version: -->
#	<!-- NetBSD: Makefile,v 1.1 2007/06/09 13:33:07 dsieger Exp   -->

# XMLDOCS+=	faq hardware index javastation
XMLDOCS+=	faq index javastation

.include "../../../share/mk/web.site.mk"
